### ISSUE TITLE
Option to mute the output in tests

### ISSUE THREAD

**Issue by pbludov** [itsallcode/junit5-system-extensions#16]
One of the problems we encountered when migrating from [system-rules](https://stefanbirkner.github.io/system-rules/) to your library is that there is no way to mute console output. See https://stefanbirkner.github.io/system-rules/index.html#SystemErrAndOutRule for the documentation. As the result, the output of the tests gets into the log.

Is it possible to add similar functionality to your library?

**Comment by pbludov** [comment]
@redcatbear ping

I can send a PR with implementation for the method `ICapturable::mute` it you are OK with this functionality.

**Comment by kaklakariada** [comment]
@pbludov Thanks for raising this issue! I talked with @redcatbear and he is ok with this. We will take care of this after the Christmas holidays.

**Comment by redcatbear** [comment]
@pbludov: Sorry for not responding sooner. I went offline (at least in respect to GitHub) over the holidays. @kaklakariada's PR looks good to me. Some small changes and we will have a new release.

**Comment by kaklakariada** [comment]
I just published version 1.1.0 to jcenter. Maven central should be synchronized soon.

**Comment by pbludov** [comment]
> I just published version 1.1.0 to jcenter. Maven central should be synchronized soon.

Thank you very much!
