### ISSUE TITLE
No more Java8 support?

### ISSUE THREAD

**Issue by pbludov** [itsallcode/junit5-system-extensions#26]
We have problems using the plugin in a Java8 project:

    [ERROR] /home/travis/build/checkstyle/checkstyle/src/test/java/com/puppycrawl/tools/checkstyle/MainTest.java:[27,49] cannot access org.itsallcode.junit.sysextensions.AssertExit
    bad class file: /home/travis/.m2/repository/org/itsallcode/junit5-system-extensions/1.2.0/junit5-system-extensions-1.2.0.jar(org/itsallcode/junit/sysextensions/AssertExit.class)
    class file has wrong version 55.0, should be 52.0

Please indicate your position on the minimum version of the JDK.

**Comment by rnveach** [comment]
Java version was changed at https://github.com/itsallcode/junit5-system-extensions/commit/f9000ddce92983163c71c67a0e29541a6fb5b26b#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8L38-R38 from 8 to 11. There was nothing in release notes to indicate a change this big.

**Comment by kaklakariada** [comment]
Sorry, you are right. We should have indicated the change. Is Java 8 a requirement for you?

**Comment by pbludov** [comment]
> Sorry, you are right. We should have indicated the change. Is Java 8 a requirement for you?

For now, yes. We are going to move forward after GSOC: https://github.com/checkstyle/checkstyle/issues/9146

**Comment by romani** [comment]
@kaklakariada , not need to downgrade to jdk8, we will migrate to new jdk soon, we can use old version for now.

**Comment by redcatbear** [comment]
@romani,  pbludov: [Version 1.2.0](https://github.com/itsallcode/junit5-system-extensions/releases/tag/1.2.0) added a delegate security manager for the `SystemExitGuard`. Unless you need that particular feature, 1.1.0 should continue to work fine.

If that is okay with you, I would close this ticket then. If your really need Java 8 support for a longer period, we would create a separate branch and maintain the Java 8 variant in parallel until [OpenJDK is officially out of support](https://endoflife.date/java) (end of 2025). I would like to invest that effort only if it is really required.

**Comment by romani** [comment]
no need to keep jdk8 support, better to spend efforts on new features, rather then on support of old jdk. 
We will migrate to jdk11 in few month too.
