### ISSUE TITLE
Fix code smells in 1.2.0

### ISSUE THREAD

**Issue by redcatbear** [itsallcode/junit5-system-extensions#27]
## Situation

The project collected a number of code smells that need to be addressed in the version up to 1.2.0

## Acceptance Criteria

1. All code smells fixed.

**Comment by kaklakariada** [comment]
Created Sonar profile ["Itsallcode way"](https://sonarcloud.io/organizations/itsallcode/quality_profiles/show?language=java&name=Itsallcode+way) based on "Sonar way", excluding [Local-Variable Type Inference should be used](https://sonarcloud.io/organizations/itsallcode/rules?activation=false&compareToProfile=AWEo96qZ6TQg_oHdEQia&languages=java&open=java%3AS6212&qprofile=AXksIVNRUHGQSgXPr1cd).

Note: new rules added to "Sonar way" will not be added to the new profile automatically, we will need to keep this in mind.
